artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion   #Path
  source_URL: https://github.com/abhishek199677/MLOPS_Wine_Project/raw/refs/heads/main/archive.zip    #str
  local_data_file: artifacts/data_ingestion/archive.zip     #Path
  unzip_dir: artifacts/data_ingestion    #Path



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation   #to save
  data_path: artifacts/data_ingestion/winequality-red.csv   #to read the file from this directory



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json